import { AlertTriangle,ShieldCheck } from 'lucide-react'
import { useEffect,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { api } from '../api/client'
import { useCart } from '../context/CartContext'

const initial={name:'',mobile:'',email:'',line1:'',line2:'',landmark:'',city:'',state:'Telangana',pincode:'',note:'',consent:false}
const DRAFT_KEY='arkmed-checkout-draft',TOKEN_KEY='arkmed-prescription-tokens',EXPIRY_KEY='arkmed-prescription-expiry'
function readDraft(){try{return {...initial,...JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'{}'),consent:false}}catch{return initial}}
const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(value)

export default function CheckoutPage(){
  const {items,count,subtotal,savings,fullyPriced,requiresPrescription,clear}=useCart();const navigate=useNavigate();const [form,setForm]=useState(readDraft);const [errors,setErrors]=useState({});const [submitting,setSubmitting]=useState(false)
  const expiry=sessionStorage.getItem(EXPIRY_KEY);const prescriptionReady=sessionStorage.getItem('arkmed-prescription-ready')==='true'&&(!expiry||new Date(expiry)>new Date())
  useEffect(()=>{const {consent:ignored,...draft}=form;void ignored;sessionStorage.setItem(DRAFT_KEY,JSON.stringify(draft))},[form])
  const change=(name,value)=>{setForm(current=>({...current,[name]:value}));setErrors(current=>({...current,[name]:undefined,submit:undefined}))}
  const submit=async event=>{event.preventDefault();if(submitting)return;const next={};const mobile=form.mobile.replace(/[\s()-]/g,'');if(form.name.trim().length<2)next.name='Enter your full name.';if(!/^\+?[0-9]{10,13}$/.test(mobile))next.mobile='Enter a valid mobile number.';if(form.email&&!/^\S+@\S+\.\S+$/.test(form.email))next.email='Enter a valid email address.';if(form.line1.trim().length<3)next.line1='Enter the delivery address.';if(form.city.trim().length<2)next.city='Enter the city.';if(form.state.trim().length<2)next.state='Enter the state.';if(!/^\d{6}$/.test(form.pincode))next.pincode='Enter a valid 6-digit pincode.';if(requiresPrescription&&!prescriptionReady)next.prescription='Upload a current prescription for the selected medicine.';if(!form.consent)next.consent='Please confirm the order and privacy terms.';if(!navigator.onLine)next.submit='You are offline. Reconnect before creating the order.';setErrors(next);if(Object.keys(next).length){setTimeout(()=>document.querySelector('[aria-invalid="true"]')?.focus(),0);return}
    const clean=value=>value.trim()||null;const payload={customer:{name:form.name.trim(),mobile,email:clean(form.email)?.toLowerCase()},address:{line1:form.line1.trim(),line2:clean(form.line2),landmark:clean(form.landmark),city:form.city.trim(),state:form.state.trim(),pincode:form.pincode},items:items.map(item=>({medicine_id:item.id,quantity:item.quantity})),prescription_upload_tokens:JSON.parse(sessionStorage.getItem(TOKEN_KEY)||'[]'),customer_note:clean(form.note)}
    setSubmitting(true);try{let result;if(import.meta.env.VITE_ENABLE_API_ORDERS==='true'){result=await api.createOrder(payload);clear();sessionStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(EXPIRY_KEY);sessionStorage.removeItem('arkmed-prescription-ready')}else result={data:{reference:'DEVELOPMENT-PREVIEW',whatsapp_url:null,subtotal,item_count:count},message:'Development preview only. No order was transmitted.'};sessionStorage.removeItem(DRAFT_KEY);sessionStorage.setItem('arkmed-order-result',JSON.stringify({...result,created_at:new Date().toISOString()}));navigate('/order-created',{replace:true})}catch(error){setErrors({submit:error.message})}finally{setSubmitting(false)}}
  const attributes={name:{autoComplete:'name'},mobile:{autoComplete:'tel',inputMode:'tel'},email:{autoComplete:'email'},line1:{autoComplete:'address-line1'},line2:{autoComplete:'address-line2'},city:{autoComplete:'address-level2'},state:{autoComplete:'address-level1'},pincode:{autoComplete:'postal-code',inputMode:'numeric'}}
  const field=(name,label,type='text',required=true)=><label htmlFor={`checkout-${name}`}>{label}{required&&' *'}<input id={`checkout-${name}`} type={type} {...attributes[name]} value={form[name]} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`error-${name}`:undefined} onChange={event=>change(name,event.target.value)}/>{errors[name]&&<small id={`error-${name}`} className="form-error">{errors[name]}</small>}</label>
  if(!items.length)return <div className="page content-width empty-state"><h1>Your cart is empty</h1><p>Add a medicine before entering delivery details.</p><Link className="button primary" to="/medicines">Browse medicines</Link></div>
  return <div className="page content-width"><div className="page-title"><span className="kicker">Guest checkout</span><h1>Delivery details</h1><p>Your draft is kept for this browser session. ARK med will confirm availability before fulfilment.</p></div><form className="checkout-layout" onSubmit={submit} noValidate><div className="form-card"><h2>Contact information</h2><div className="form-grid">{field('name','Full name')}{field('mobile','Mobile number','tel')}{field('email','Email address','email',false)}</div><h2>Delivery address</h2><div className="form-grid">{field('line1','Address line 1')}{field('line2','Address line 2','text',false)}{field('landmark','Landmark','text',false)}{field('city','City')}{field('state','State')}{field('pincode','Pincode')}</div><label htmlFor="checkout-note">Customer note <small>{form.note.length}/1000</small><textarea id="checkout-note" value={form.note} maxLength="1000" onChange={event=>change('note',event.target.value)} placeholder="Delivery instructions or questions for the pharmacist"/></label></div><aside className="order-summary"><div className="summary-title"><h2>Review order</h2><Link to="/cart">Edit cart</Link></div><ul className="checkout-lines">{items.map(item=><li key={item.id}><span>{item.name}<small>Qty {item.quantity}</small></span><strong>{item.price!=null?money(Number(item.price)*item.quantity):'To confirm'}</strong></li>)}</ul><p><span>Total items</span><strong>{count}</strong></p>{fullyPriced?<p><span>Estimated subtotal</span><strong>{money(subtotal)}</strong></p>:<p><span>Amount</span><strong>Confirmed on WhatsApp</strong></p>}{savings>0&&<p className="savings"><span>Estimated savings</span><strong>{money(savings)}</strong></p>}{requiresPrescription&&<p className={prescriptionReady?'prescription-ok':'availability-warning'}><AlertTriangle/> {prescriptionReady?'Prescription attached':'Prescription required'}</p>}{errors.prescription&&<p className="form-error" role="alert">{errors.prescription} <Link to="/upload-prescription">Upload now</Link></p>}<label className="checkout-consent"><input type="checkbox" checked={form.consent} aria-invalid={Boolean(errors.consent)} onChange={event=>change('consent',event.target.checked)}/><span>I confirm these details and agree to the <Link to="/content/terms">terms</Link> and <Link to="/content/privacy-policy">privacy policy</Link>.</span></label>{errors.consent&&<small className="form-error">{errors.consent}</small>}{errors.submit&&<p className="form-error" role="alert">{errors.submit}</p>}<p className="privacy-note"><ShieldCheck/> Details are used only to process this order.</p><button className="button primary" disabled={submitting}>{submitting?'Creating order…':'Create order'}</button><small>The server creates your ARK reference before WhatsApp.</small></aside></form></div>
}
