import { ChevronRight, HeartPulse, MessageCircle, Pill, ShieldCheck, Stethoscope, Upload } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect,useState } from 'react'
import { categories, sampleMedicines } from '../data'
import MedicineCard from '../components/MedicineCard'
import { api } from '../api/client'
import { normaliseMedicine } from '../utils/medicine'
import Seo from '../components/Seo'
export default function HomePage(){const live=import.meta.env.VITE_ENABLE_LIVE_CATALOGUE==='true';const [home,setHome]=useState(null);const [recent]=useState(()=>{try{const value=JSON.parse(localStorage.getItem('arkmed-recent-v1')||'[]');return Array.isArray(value)?value.filter(item=>item?.id&&item?.slug).slice(0,3):[]}catch{return[]}});useEffect(()=>{if(live)api.home().then(result=>setHome(result.data)).catch(()=>{})},[live]);const displayCategories=home?.categories?.map((category,index)=>({...category,icon:categories[index%categories.length]?.icon||'💊',tone:categories[index%categories.length]?.tone||'blue',image:categories[index%categories.length]?.image}))||categories;const featured=home?.featured_medicines?.map(normaliseMedicine)||sampleMedicines.slice(0,3);const banner=home?.banners?.[0];return <><Seo title="Pharmacy & Clinic" description="Order medicines, upload prescriptions and request clinic services from ARK med Pharmacy & Clinic."/>
  <section className="hero content-width"><div className="hero-media" aria-hidden="true"><img src={banner?.desktop_image||'/hero-healthcare.webp'} alt="" width="1600" height="667" fetchPriority="high"/></div><div className="hero-copy"><span className="eyebrow"><ShieldCheck size={17}/> Trusted pharmacy care</span><h1>{banner?.title||<>Your Health<br/><em>Our Priority</em></>}</h1><p>{banner?.subtitle||'Order medicines online, consult doctors and book health checkups—all in one place.'}</p><div className="hero-actions"><Link className="button primary" to={banner?.cta_url||'/medicines'}><Pill/> {banner?.cta_text||'Order Medicines'} <ChevronRight/></Link><Link className="button secondary" to="/upload-prescription"><Upload/> Upload Prescription</Link></div><div className="hero-service-links"><Link to="/doctor-consultation"><Stethoscope/> Doctor consultation</Link><Link to="/health-checkups"><HeartPulse/> Health checkups</Link></div></div></section>
  <section className="quick-actions content-width" aria-label="Quick actions">{[[Pill,'Medicines','/medicines'],[Upload,'Upload Prescription','/upload-prescription'],[Stethoscope,'Doctor Consultation','/doctor-consultation'],[HeartPulse,'Health Checkups','/health-checkups'],[MessageCircle,'WhatsApp Order','/cart']].map(([Icon,label,to])=><Link to={to} key={label}><span><Icon/></span><strong>{label}</strong></Link>)}</section>
  <section className="section content-width" id="categories"><div className="section-heading"><div><span className="kicker">Browse easily</span><h2>Shop by Category</h2></div><Link to="/medicines">View all <ChevronRight/></Link></div><div className="category-grid">{displayCategories.map(c=><Link className={`category-card ${c.tone}`} to={`/medicines?category=${c.slug}`} key={c.slug}><div className="category-image">{c.image?<img src={c.image} alt="" width="520" height="520" loading="lazy"/>:<span>{c.icon}</span>}</div><strong>{c.name}</strong></Link>)}</div></section>
  <section className="section content-width"><div className="section-heading"><div><span className="kicker">{live?'From our catalogue':'Catalogue preview'}</span><h2>Popular Medicines</h2></div><Link to="/medicines">View all <ChevronRight/></Link></div>{!live&&<p className="verification-note"><ShieldCheck/> Product details and prices will appear after pharmacy verification.</p>}<div className="medicine-grid">{featured.map(m=><MedicineCard medicine={m} key={m.id}/>)}</div></section>
  {recent.length>0&&<section className="section content-width"><div className="section-heading"><div><span className="kicker">Continue browsing</span><h2>Recently viewed</h2></div></div><div className="medicine-grid">{recent.slice(0,3).map(m=><MedicineCard medicine={m} key={m.id}/>)}</div></section>}
  <section className="whatsapp content-width"><span className="whatsapp-icon"><MessageCircle/></span><div className="whatsapp-copy"><h2>Order on WhatsApp</h2><p>Send your prescription or medicine list on WhatsApp and we'll take care of the rest!</p></div><Link to="/cart">Chat on WhatsApp <ChevronRight/></Link><div className="whatsapp-phone" aria-hidden="true"><span><MessageCircle/></span></div></section>
  <section className="section health-services content-width" id="services"><div className="section-heading"><div><h2>Our Health Services</h2></div></div><div className="service-grid"><Link to="/doctor-consultation"><span><Stethoscope/></span><div><h3>Book Consultation</h3><p>Consult experienced doctors online or in-clinic</p></div><b><ChevronRight/></b></Link><Link to="/health-checkups"><span><HeartPulse/></span><div><h3>Book Health Checkup</h3><p>Full body checkups at special prices</p></div><b><ChevronRight/></b></Link></div></section>
  </>}
