import { lazy,Suspense } from 'react'
import { BrowserRouter,Route,Routes } from 'react-router-dom'
import AdminLayout from './components/AdminLayout'
import AdminRoute from './components/AdminRoute'
import Layout from './components/Layout'
import RouteEffects from './components/RouteEffects'
import { AdminAuthProvider } from './context/AdminAuthContext'
import { CartProvider } from './context/CartContext'
import { FavouritesProvider } from './context/FavouritesContext'

const HomePage=lazy(()=>import('./pages/HomePage')),CataloguePage=lazy(()=>import('./pages/CataloguePage')),MedicinePage=lazy(()=>import('./pages/MedicinePage')),CartPage=lazy(()=>import('./pages/CartPage')),PrescriptionPage=lazy(()=>import('./pages/PrescriptionPage')),CheckoutPage=lazy(()=>import('./pages/CheckoutPage')),OrderSuccessPage=lazy(()=>import('./pages/OrderSuccessPage')),NotFoundPage=lazy(()=>import('./pages/NotFoundPage')),ServicePage=lazy(()=>import('./pages/ServicePage')),DynamicPage=lazy(()=>import('./pages/DynamicPage')),FavouritesPage=lazy(()=>import('./pages/FavouritesPage')),OrderTrackingPage=lazy(()=>import('./pages/OrderTrackingPage'))
const AdminLoginPage=lazy(()=>import('./pages/admin/AdminLoginPage')),AdminDashboardPage=lazy(()=>import('./pages/admin/AdminDashboardPage')),AdminMedicinesPage=lazy(()=>import('./pages/admin/AdminMedicinesPage')),AdminCategoriesPage=lazy(()=>import('./pages/admin/AdminCategoriesPage')),AdminOrdersPage=lazy(()=>import('./pages/admin/AdminOrdersPage')),AdminPrescriptionsPage=lazy(()=>import('./pages/admin/AdminPrescriptionsPage')),AdminSettingsPage=lazy(()=>import('./pages/admin/AdminSettingsPage')),AdminImportsPage=lazy(()=>import('./pages/admin/AdminImportsPage')),AdminUsersPage=lazy(()=>import('./pages/admin/AdminUsersPage')),AdminAuditPage=lazy(()=>import('./pages/admin/AdminAuditPage')),AdminContentPage=lazy(()=>import('./pages/admin/AdminContentPage')),AdminEnquiriesPage=lazy(()=>import('./pages/admin/AdminEnquiriesPage')),AdminMediaPage=lazy(()=>import('./pages/admin/AdminMediaPage')),AdminProfilePage=lazy(()=>import('./pages/admin/AdminProfilePage'))

function RouteLoader(){return <div className="route-loader" role="status" aria-live="polite"><img src="/arkmed-mark.svg" alt=""/><span>Loading…</span></div>}
export default function App(){return <BrowserRouter><RouteEffects/><AdminAuthProvider><FavouritesProvider><CartProvider><Suspense fallback={<RouteLoader/>}><Routes><Route element={<Layout/>}><Route path="/" element={<HomePage/>}/><Route path="/medicines" element={<CataloguePage/>}/><Route path="/medicines/:slug" element={<MedicinePage/>}/><Route path="/favourites" element={<FavouritesPage/>}/><Route path="/cart" element={<CartPage/>}/><Route path="/upload-prescription" element={<PrescriptionPage/>}/><Route path="/checkout" element={<CheckoutPage/>}/><Route path="/order-created" element={<OrderSuccessPage/>}/><Route path="/track-order" element={<OrderTrackingPage/>}/><Route path="/doctor-consultation" element={<ServicePage type="doctor_consultation"/>}/><Route path="/health-checkups" element={<ServicePage type="health_checkup"/>}/><Route path="/contact" element={<ServicePage type="contact"/>}/><Route path="/content/:slug" element={<DynamicPage/>}/><Route path="*" element={<NotFoundPage/>}/></Route><Route path="/admin/login" element={<AdminLoginPage/>}/><Route element={<AdminRoute/>}><Route element={<AdminLayout/>}><Route path="/admin" element={<AdminDashboardPage/>}/><Route path="/admin/profile" element={<AdminProfilePage/>}/><Route path="/admin/medicines" element={<AdminMedicinesPage/>}/><Route path="/admin/categories" element={<AdminCategoriesPage/>}/><Route path="/admin/imports" element={<AdminImportsPage/>}/><Route path="/admin/orders" element={<AdminOrdersPage/>}/><Route path="/admin/prescriptions" element={<AdminPrescriptionsPage/>}/><Route path="/admin/enquiries" element={<AdminEnquiriesPage/>}/><Route path="/admin/content" element={<AdminContentPage/>}/><Route path="/admin/media" element={<AdminMediaPage/>}/><Route path="/admin/settings" element={<AdminSettingsPage/>}/><Route path="/admin/users" element={<AdminUsersPage/>}/><Route path="/admin/audit" element={<AdminAuditPage/>}/></Route></Route></Routes></Suspense></CartProvider></FavouritesProvider></AdminAuthProvider></BrowserRouter>}
